name: Publish to docker.pkg.github.com

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: aktriver
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com/aktriver/dotfiles/dotfiles
        tag_with_ref: true
